### DISCUSSION TITLE
Unable to distribute doctr training across multiple GPU

### DISCUSSION THREAD

**Discussion by sarjil77** [mindee/doctr#1771] [Q&A] [answered]
Hello,
I am trying to fine tune for the text detection using db_resnet_50 using pytorch, the issue is i have only 100 training images and when i am trying to fine tune using it, i am getting out of memory error. The reason is it is only able to use only 1 GPU which is of 48GB, it is not utilizing the multiple GPU, is there any way how can i use multiple GPU when finetuning, and i do not understand why it requires so much of memory, infact model is not that large and i am also using batch size of 1.

PLease provide necessary suggestion and solution

thanks in advance

**Comment by felixdittrich92** [comment, marked as answer]
Hi @sarjil77 👋 ,,

We have only a DDP train script for the recognition task atm but you could easily adapt the detection train script with the required changes on your own :)
Here is the script: https://github.com/mindee/doctr/blob/main/references/recognition/train_pytorch_ddp.py


Normaly you can fit a batch size of 2 in 16 gb VRAM... If you start the script with --show-samples everything looks correct ?

**Comment by sarjil77** [comment]
thanks felix for your above response, i have tried with my own DDP script it didnt work, and i will try with your script as well.
now the issue is when i have trained my db_resent_50 model and put the input_size as 256 instead of default 1024, so when i am loading this custom fintuned model it is giving me error related to mismatch in model dimension.

I am giving my full logs for your reference:
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[19], [line 6](vscode-notebook-cell:?execution_count=19&line=6)
      [4](vscode-notebook-cell:?execution_count=19&line=4) det_model = db_resnet50(pretrained=False, pretrained_backbone=False)
      [5](vscode-notebook-cell:?execution_count=19&line=5) det_params = torch.load('/data/aiuserinj/sarjil/doctr/references/detection/db_resnet50_20241107-182101.pt', map_location="cpu")
----> [6](vscode-notebook-cell:?execution_count=19&line=6) det_model.load_state_dict(det_params)
      [7](vscode-notebook-cell:?execution_count=19&line=7) predictor = ocr_predictor(det_arch=det_model, reco_arch="vitstr_small", pretrained=True)

File ~/anaconda3/envs/sarjil_dev/lib/python3.11/site-packages/torch/nn/modules/module.py:2584, in Module.load_state_dict(self, state_dict, strict, assign)
   [2576](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a2241494d4c4445565f474c4f42414c227d.vscode-resource.vscode-cdn.net/data/aiuserinj/sarjil/OCR_development/~/anaconda3/envs/sarjil_dev/lib/python3.11/site-packages/torch/nn/modules/module.py:2576)         error_msgs.insert(
   [2577](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a2241494d4c4445565f474c4f42414c227d.vscode-resource.vscode-cdn.net/data/aiuserinj/sarjil/OCR_development/~/anaconda3/envs/sarjil_dev/lib/python3.11/site-packages/torch/nn/modules/module.py:2577)             0,
   [2578](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a2241494d4c4445565f474c4f42414c227d.vscode-resource.vscode-cdn.net/data/aiuserinj/sarjil/OCR_development/~/anaconda3/envs/sarjil_dev/lib/python3.11/site-packages/torch/nn/modules/module.py:2578)             "Missing key(s) in state_dict: {}. ".format(
   [2579](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a2241494d4c4445565f474c4f42414c227d.vscode-resource.vscode-cdn.net/data/aiuserinj/sarjil/OCR_development/~/anaconda3/envs/sarjil_dev/lib/python3.11/site-packages/torch/nn/modules/module.py:2579)                 ", ".join(f'"{k}"' for k in missing_keys)
   [2580](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a2241494d4c4445565f474c4f42414c227d.vscode-resource.vscode-cdn.net/data/aiuserinj/sarjil/OCR_development/~/anaconda3/envs/sarjil_dev/lib/python3.11/site-packages/torch/nn/modules/module.py:2580)             ),
   [2581](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a2241494d4c4445565f474c4f42414c227d.vscode-resource.vscode-cdn.net/data/aiuserinj/sarjil/OCR_development/~/anaconda3/envs/sarjil_dev/lib/python3.11/site-packages/torch/nn/modules/module.py:2581)         )
   [2583](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a2241494d4c4445565f474c4f42414c227d.vscode-resource.vscode-cdn.net/data/aiuserinj/sarjil/OCR_development/~/anaconda3/envs/sarjil_dev/lib/python3.11/site-packages/torch/nn/modules/module.py:2583) if len(error_msgs) > 0:
-> [2584](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a2241494d4c4445565f474c4f42414c227d.vscode-resource.vscode-cdn.net/data/aiuserinj/sarjil/OCR_development/~/anaconda3/envs/sarjil_dev/lib/python3.11/site-packages/torch/nn/modules/module.py:2584)     raise RuntimeError(
   [2585](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a2241494d4c4445565f474c4f42414c227d.vscode-resource.vscode-cdn.net/data/aiuserinj/sarjil/OCR_development/~/anaconda3/envs/sarjil_dev/lib/python3.11/site-packages/torch/nn/modules/module.py:2585)         "Error(s) in loading state_dict for {}:\n\t{}".format(
   [2586](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a2241494d4c4445565f474c4f42414c227d.vscode-resource.vscode-cdn.net/data/aiuserinj/sarjil/OCR_development/~/anaconda3/envs/sarjil_dev/lib/python3.11/site-packages/torch/nn/modules/module.py:2586)             self.__class__.__name__, "\n\t".join(error_msgs)
   [2587](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a2241494d4c4445565f474c4f42414c227d.vscode-resource.vscode-cdn.net/data/aiuserinj/sarjil/OCR_development/~/anaconda3/envs/sarjil_dev/lib/python3.11/site-packages/torch/nn/modules/module.py:2587)         )
   [2588](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a2241494d4c4445565f474c4f42414c227d.vscode-resource.vscode-cdn.net/data/aiuserinj/sarjil/OCR_development/~/anaconda3/envs/sarjil_dev/lib/python3.11/site-packages/torch/nn/modules/module.py:2588)     )
   [2589](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a2241494d4c4445565f474c4f42414c227d.vscode-resource.vscode-cdn.net/data/aiuserinj/sarjil/OCR_development/~/anaconda3/envs/sarjil_dev/lib/python3.11/site-packages/torch/nn/modules/module.py:2589) return _IncompatibleKeys(missing_keys, unexpected_keys)

RuntimeError: Error(s) in loading state_dict for DBNet:
	size mismatch for prob_head.6.weight: copying a param with shape torch.Size([64, 1904, 2, 2]) from checkpoint, the shape in current model is torch.Size([64, 1, 2, 2]).
	size mismatch for prob_head.6.bias: copying a param with shape torch.Size([1904]) from checkpoint, the shape in current model is torch.Size([1]).
	size mismatch for thresh_head.6.weight: copying a param with shape torch.Size([64, 1904, 2, 2]) from checkpoint, the shape in current model is torch.Size([64, 1, 2, 2]).
	size mismatch for thresh_head.6.bias: copying a param with shape torch.Size([1904]) from checkpoint, the shape in current model is torch.Size([1]).
	
	
----------------------thanks in advance----------------

and also i have tried to filtering out DBNet specific layers and code ran but the response is not even 1%

**Reply by felixT2K** [reply]
I wouldn't suggest to change the input_size ..256 is much to small to extract enough features.

What's the input sizes of your documents/images ?

**Comment by felixT2K** [comment]
with a changed input size you would need to modify the PreProcessor 

snippet:

```
import torch
from doctr.models.predictor import OCRPredictor
from doctr.models.detection.predictor import DetectionPredictor
from doctr.models.preprocessor import PreProcessor
from doctr.models import db_resnet50

det_model = db_resnet50(pretrained=False, pretrained_backbone=False)
det_params = torch.load('/data/aiuserinj/sarjil/doctr/references/detection/db_resnet50_20241107-182101.pt', map_location="cpu")
det_model.load_state_dict(det_params)

det_predictor = DetectionPredictor(
    PreProcessor(
        (256, 256),  # Changed to your input_size
        batch_size=1,
        mean=(0.798, 0.785, 0.772),
        std=(0.264, 0.2749, 0.287)
    ),
    det_model
)

predictor = OCRPredictor(det_predictor, reco_predictor, reco_arch="vitstr_small", pretrained=True)
```

**Reply by sarjil77** [reply]
Thank u sir, 
I am getting the same error using script above. I will check from my side.

**Comment by felixT2K** [comment]
Quickly validated i can easily fit a batch size of 4 with large images ...
![Screenshot from 2024-11-08 13-56-17](https://github.com/user-attachments/assets/9c03c6a5-6f78-4ba3-b493-6da0e3b848c3)
![Screenshot from 2024-11-08 13-55-58](https://github.com/user-attachments/assets/c0d685e1-eef2-43bf-b0ef-a2f27dc919cf)

**Reply by felixT2K** [reply]
If you start the train script with `--show-samples` looks everything fine ? 

Anywhere i have the bad feeling that something with your annotations isn't correct .. which results in really large arrays --> OOM

**Reply by felixT2K** [reply]
We provide by the way reference datasets you could use for validation: https://github.com/mindee/doctr/discussions/1654

(If with these provided dataset it still goes OOM then something with your host machine isn't well working ^^)

**Reply by sarjil77** [reply]
I have validated my annotations once before putting it for training, i will also look if there is any issue from my side.

**Reply by sarjil77** [reply]
thanks @felixT2K, it is working now properly.
